holidays:
  1:
    - 1   # 元旦
    - 2   # 元旦彈性
  2:
    - 18  # 除夕
    - 19  # 春節
    - 20  # 春節
    - 23  # 春節
    - 27  # 228 補假
  4:
    - 3   # 兒童節補假
    - 6   # 清明補假
  5:
    - 1   # 勞動節
  6:
    - 19  # 端午補假
  9:
    - 28  # 中秋補假
  10:
    - 9   # 國慶補假
makeup_days:
