holidays:
  1:
    - 1   # 元旦
  2:
    - 8   # 春節
    - 9   # 春節
    - 10  # 春節
    - 11  # 春節
    - 12  # 春節彈性
    - 29  # 228 補假
  4:
    - 4   # 兒童節
    - 5   # 清明補假
  5:
    - 2   # 勞動節補假
  6:
    - 9   # 端午節
    - 10  # 端午彈性
  9:
    - 15  # 中秋節
    - 16  # 中秋彈性
  10:
    - 10  # 國慶日
makeup_days:
  1:
    - 30  # 春節補班
  6: 
    - 4   # 端午補班
  9:
    - 10  # 中秋補班
