holidays:
  1:
    - 2   # 元旦補假
    - 27  # 除夕
    - 30  # 春節
    - 31  # 春節補假
  2:
    - 1   # 春節補假
    - 27  # 228 彈性
    - 28  # 228
  4:
    - 3   # 兒童節
    - 4   # 清明
  5:
    - 1   # 勞動節
    - 28  # 端午彈性
    - 29  # 端午節
  10:
    - 4   # 中秋節
    - 9   # 國慶彈性
    - 10  # 國慶日
makeup_days:
  2:
    - 18  # 228 補班
  6: 
    - 3   # 端午補班
  9:
    - 30  # 國慶補班
