holidays:
  1:
    - 1   # 元旦
  2:
    - 15  # 除夕
    - 16  # 春節
    - 19  # 春節
    - 20  # 春節
    - 28  # 228
  4:
    - 4   # 兒童節
    - 5   # 清明
    - 6   # 清明彈性
  5:
    - 1   # 勞動節
  6:
    - 18  # 端午節
  9:
    - 24  # 中秋節
  10:
    - 10  # 國慶日
  12:
    - 31  # 元旦彈性
makeup_days:
  3:
    - 31  # 清明補班
  12:
    - 22  # 元旦補班
