holidays:
  1:
    - 1   # 元旦
  2:
    - 4   # 除夕
    - 5   # 春節
    - 6   # 春節
    - 7   # 春節
    - 8   # 春節
    - 28  # 228
  3:
    - 1   # 228彈性
  4:
    - 4   # 兒童節
    - 5   # 清明
  5:
    - 1   # 勞動節
  6:
    - 7   # 端午節
  9:
    - 13  # 中秋節
  10:
    - 10  # 國慶日
    - 11  # 國慶日彈性
makeup_days:
  1:
    - 19  # 春節補班
  2:
    - 23  # 228補班
  10:
    - 5   # 國慶日補班
